spring:
  application:
    name: sprb-eureka

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://sprb-eureka.ula.app.cloud.comcast.net/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
