spring:
  application:
    name: sprb_demo_turbine

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
    org.springframework.integration: INFO
    com.netflix.discovery: 'OFF'

server:
  port: 8989

management:
  port: 8990

eureka:  
  password: password
  server:
    port: 8761
  client:
    serviceUrl:
      defaultZone: http://user:${eureka.password}@localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}      
